### ISSUE TITLE
stanity requirement

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/survivalstan#4] opened 2016-07-06 17:56 UTC
`git clone`ing this repo and then `pip install -e .` does not result in `stanity` being installed, even though it seems like it should based on the `setup.py` code. Not sure why?

**Comment by jburos** [comment] 2016-07-13 18:41
This is in the `requirements`; I'll need to look into why it isn't being installed

**Comment by tavinathanson** [comment] 2016-07-13 21:11
Yeah, noticed that; curious if you can reproduce the issue, otherwise I can poke more on my side.

**Comment by jburos** [comment] 2016-07-14 02:25
I am able to reproduce it - I believe it's due to poor parsing of the `requirements.txt` file in setup.py. Will investigate. Thanks for the report!!

**Comment by jburos** [comment] 2016-07-14 21:43
Looks like the solution to this issue is to publish `stanity` to pypi

**Comment by jburos** [comment] 2016-07-15 22:44
This should be fixed now that stanity has been pushed to pypi - this commit (b4765261ab85edb1f7a4290eda8f48c5be4f2897) updated the requirement.

**Comment by jburos** [comment] 2016-07-16 17:04
The install appears to still be problematic, in that 

(1) [stanity](http://github.com/hammerlab/stanity) does install, **but**
(2) `pystan` does not 

Cross-referencing issue & output at hammerlab/stanity#10. This may be an error in `survivalstan`, `stanity` or both.

**Closed** 2016-08-08 16:46 UTC
Labels: bug
