### ISSUE TITLE
Unknown compilation issue

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/survivalstan#44] opened 2017-01-09 19:01 UTC
I ran into a compilation issue when running the following on my Mac, from the README (seems to work on Linux):

```
## e.g. fit Weibull survival model
testfit_wei = survivalstan.fit_stan_survival_model(
    model_cohort = 'Weibull model',
    model_code = survivalstan.models.weibull_survival_model,
    df = d,
    time_col = 'futime',
    event_col = 'death',
    formula = 'age + sex',
    iter = 3000,
    chains = 4,
    make_inits = survivalstan.make_weibull_survival_model_inits
    )
```

I'll try to post the stack trace and associated errors when I reproduce.

**Comment by jburos** [comment] 2017-01-09 19:56
Thanks @tavinathanson

Historically there have been issues [installing pystan on a mac](https://github.com/stan-dev/pystan/issues?utf8=%E2%9C%93&q=is%3Aissue%20mac). 

Can you try the following example code ([provided by pystan](http://pystan.readthedocs.io/en/latest/getting_started.html)) & let me know if this works?  This may help isolate the issue.

```
schools_code = """
data {
    int<lower=0> J; // number of schools
    real y[J]; // estimated treatment effects
    real<lower=0> sigma[J]; // s.e. of effect estimates
}
parameters {
    real mu;
    real<lower=0> tau;
    real eta[J];
}
transformed parameters {
    real theta[J];
    for (j in 1:J)
    theta[j] <- mu + tau * eta[j];
}
model {
    eta ~ normal(0, 1);
    y ~ normal(theta, sigma);
}
"""

schools_dat = {'J': 8,
               'y': [28,  8, -3,  7, -1,  1, 18, 12],
               'sigma': [15, 10, 16, 11,  9, 11, 10, 18]}

fit = pystan.stan(model_code=schools_code, data=schools_dat,
                  iter=1000, chains=4)

```

**Comment by jburos** [comment] 2018-09-05 19:58
Closing this issue since we are unable to reproduce it.

**Closed by jburos** 2018-09-05 19:58 UTC
Labels: bug
